# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='label'),
        ),
    ]
