# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_responsefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='related',
            field=models.BooleanField(default=False, verbose_name='realted'),
        ),
    ]
